### ISSUE TITLE
New-AzureRmResourceGroup fails with V2 template building blocks

### ISSUE THREAD

**Issue by iaasazure** [mspnp/template-building-blocks#320]
I am testing using simple vnet scenarios as shown in the example scenarios.  New-AzureRmResourceGroup fails with V2 template building blocks.  This code works using the V1 templates and associated V1 parameter files.

the following works:
azbb -g TestResourceGroup -s aaa-aaaa-aaa 5 -l westeurope --deploy -p .\virtualNetworkV2-mod.parameters.json

New-AzureRmResourceGroup with the same template fails and requests deploymentcontext object and virtualnetworks object.
$resgroup = New-AzureRmResourceGroup -Name TestResourceGroup -Location westeurope
New-AzureRmResourceGroupDeployment -Name Deploy-SampleVnetV2 -ResourceGroupName $resgroup -Mode Incremental `
-DeploymentDebugLogLevel All -TemplateParameterFile D:\temp\virtualNetworkV2-mod.parameters.json `
-TemplateUri https://raw.githubusercontent.com/mspnp/template-building-blocks/master/templates/buildingBlocks/virtualNetworks/virtualNetworks.json -Verbose -WhatIf

Please could someone show what is needed to operate the templates using powershell?
Thanks

**Comment by atoakley** [comment]
The parameter files for azbb cannot be used directly in the templates.  If you would like to use the output of the azbb parameter processing to deploy from PowerShell, you would have to do the following:

1. Run the azbb command without the deploy switch.  This will create one or more output files, depending on what was in the azbb parameter file
```
azbb -g TestResourceGroup -s aaa-aaaa-aaa 5 -l westeurope
```
2. Create all of the resource groups that will be required for the resource group deployments (there can be multiple due to how subscription, resource group, and location can be overridden in azbb parameter files)
3. Using the correct resource group for each deployment, pass each of the output files to the correct template.  The template to use be different depending on which building block type was used for each set of settings, so you would need to know which output file was associated to which building block.

We added the --deploy switch to automate these steps because there is some metadata carried within the tool that makes this simpler.  However, that metadata is not present in generated template parameter files.

What is your use case for deploying them with PowerShell instead of using the --deploy switch?

**Comment by iaasazure** [comment]
Thanks Andrew.  I used the template building blocks v1 with powershell to dynamically build the parameter file based on a CSV or with multiple VM's and load balancers etc.  I had multiple CSV files for different deployments, I would create a CSV in 5 minutes for each project and quickly could deploy all my azure VM's, load balancers with the correct public IP's etc.  It seems like this will not work using the V2 templates unless I use powershell to drive the azbb tool.  for this to work I would need to work out how to save a file in JSON format as at the moment I have a powershell template parameter object.  I also get issues with driving azbb from powershell ISE, Visual studio code or visual studio.  Perhaps I am going about this the wrong way.  Would you have any suggestions for the most efficient way to create azure resources from some basic inputs such as VM name, OS image etc and how to create the parameter files programmatically?

**Comment by Petertaylor9999** [comment]
Hi there - we'd like to know a little more about your scenario. 

Are you authoring the parameter values in a CSV file and then transforming them to V1 parameter JSON files?

**Comment by jachin84** [comment]
I was also trying to use this tool with New-AzureRmResourceGroupDeployment only to find that's not really the intention. I have some scripts similar in behavior to [this one](https://github.com/Azure/azure-quickstart-templates/blob/master/Deploy-AzureResourceGroup.ps1) in the [azure-quickstart-templates](https://github.com/Azure/azure-quickstart-templates/) repo. It would be nice if azbb could output both the template and the parameter files for a deployment with New-AzureRmResourceGroupDeployment. 

Given that most of the guidance on ARM template deployment pushes down the Azure PowerShell or Azure Cli route it does seem a little inconsistent to have yet another tool. For me it was actually a disincentive to use the tool because it doesn't integrate with my existing process and tools (Azure PowerShell, C#, uploading templates to storage accounts, sasTokens, etc.)

On the other hand what you have done with splitting up the templates into small reusable blocks is really impressive and well worth the effort to integrating with my existing process. I wonder if it would be better to try and extract these building blocks out further to be agnostic of the deployment tool? As it stands today I have to use azbb to deploy these templates and as a Windows ITPro I'm just not that into `'npm install blah'`.

**Comment by telmosampaio** [comment]
@jachin84, azbb is an abstraction layer on top of templates. We chose node as a developer platform for this open source project because at the time the CLI was in node. We chose to use CLI instead of PowerShell to provide the same experience and code base, independent of whether customers are using Windows, MacOS, or Linux. As an IT Pro, you can think of npm install and installing a PowerShell module. 

Some of the tools you mentioned are supported by azbb, such as the use of sastokens, uploading templates and parameter files to storage accounts, etc. And you CAN use the output files from azbb as parameter files to deploy from PowerShell using New-AzureRmResourceGroupDeployment. All you have to do is use the endpoints for the ARM templates, which are in the templates folder.

**Comment by jachin84** [comment]
I understand what you're saying and please don't take my remarks as a criticism in any way. I think this approach to ARM templates is the best I've seen so far. The challenge I think you may have is buy-in from the broader community. I'm quite familiar with node and npm however I know many of my fellow Windows ITPros do not even have Node installed. 

I've noted that is a perception amongst developers that everyone knows and uses node and npm and similar cross-platform tools. I'm in a DevOps role so I'm familiar with these tools however must Windows admins are not. Remember that a very large portion of Azure customers will be traditional Windows IT Pros, many of which will have never even heard of these tools let alone know how to use them.

If you're looking to target only developers then you're probably right on the money. If you audience is broader then that perhaps having something a little more familiar for the Windows IT Pros would be the way to go.

Thinking out loud if you used .net core you could have an executable that would work on Linux, MacOS or Linux and you could have a PowerShell module that references the same code. I know PowerShell is also cross-platform now so maybe that is a viable option.

Anyway, even an additional arguments that allows azbb to collects all the required template files and emit them to a local folder would be a step in the right direction.
