### ISSUE TITLE
Enhancement: virtualMachineSettings: customData

### ISSUE THREAD

**Issue by chen23** [mspnp/template-building-blocks#363]
Does the template support "customData" for linux VMs?

Trying the following:

```
{
              "type": "VirtualMachine",
              "settings": {
                "vmCount": 1,
                "namePrefix": "linux",
                "size": "Standard_DS2_v2",
                "adminUsername": "chen",
                "adminPassword": "...",
                "customData":"foobar",
```

Getting:

```
                "osProfile": {
                  "adminUsername": "chen",
                  "secrets": [],
                  "adminPassword": "$AUTHENTICATION$",
                  "linuxConfiguration": null,
                  "computerName": "linux-vm1"
                },
```
Expecting:

```
                "osProfile": {
                  "adminUsername": "chen",
                  "secrets": [],
                  "adminPassword": "$AUTHENTICATION$",
                  "customData": "foobar",
                  "linuxConfiguration": null,
                  "computerName": "linux-vm1"
                },
```

Thank you.

**Comment by atoakley** [comment]
We have added support for this in PR #365.  We will have the v2.1.2 npm package published soon.  Please note that the string in the customData field must be base64 encoded because the templates require it that way.  Assuming you are on a linux machine, build the cloud-init config as normal, run "base64 -w 0 &lt;cloud-config-file&gt;", and paste the resulting base64 string into the customData field.  If there are any issues with the config, you can see them in /var/log/cloud-init.log and /var/log/cloud-init-output.log on the linux VMs that get created.
