### ISSUE TITLE
NSG issue

### ISSUE THREAD

**Issue by merewind** [mspnp/template-building-blocks#376]
NSG rule priority does not seem to work.

**Comment by telmosampaio** [comment]
Can yo please provide an example of what you mean?

**Comment by merewind** [comment]
regardless of priority set in the configuration the resulted priority is  set as 100, 110, 120 etc for each security rule...

**Comment by atoakley** [comment]
@merewind We do not respect the priority if it exists in the parameter files.  We renumber them and leave holes just in case a new rule needs to be added after the fact.  Because we have the named rules that can expand into more than one rule, there could end up being rules intermixed if we let users give arbitrary priorities.  The rules will be auto-numbered (by 10s) in the order in which they appear in the parameter file.  Do you have a use case where this doesn't fit?

**Comment by merewind** [comment]
Perhaps it will work @atoakley, it's just a bit confusing that docs are have mention of priority. We will do some more testing and report issues. 
On this topic of NSGs with now GA for [ Augmented NSG rules](https://azure.microsoft.com/en-us/updates/agumented-rules-ga-nsg/) it will be great if azbb can support that which will be a great improvement.

**Comment by telmosampaio** [comment]
I will keep this open as a request for Augmented NSGs for our next cycle.

**Comment by hallihan** [comment]
Closing as we are not implementing new features in azbb, se note in #435
