### ISSUE TITLE
"env: node\r: No such file or directory" issue 

### ISSUE THREAD

**Issue by easkerov** [mspnp/template-building-blocks#386]
I have an issue running `azbb` on macOS X (High Sierra 10.13.4).

I've successfully installed tool:

```
$ npm install -g @mspnp/azure-building-blocks
/usr/local/bin/azbb -> /usr/local/lib/node_modules/@mspnp/azure-building-blocks/src/index.js
/usr/local/lib
└─┬ @mspnp/azure-building-blocks@2.1.5 
  ├── commander@2.15.1 
  ├── lodash@4.17.10 
  ├── murmurhash3js@3.0.1 
  └── semver@5.5.0 

```

But unable to run. I got the following error:

```
$ azbb -V
env: node\r: No such file or directory
```
Node version: v6.14.1
npm version: 3.10.10

**Comment by luisgmsft** [comment]
Hi @easkerov :) There was an issue with the package. Try with the latest one ([v.2.1.7](https://www.npmjs.com/package/@mspnp/azure-building-blocks))

Please let me know if this helps!

**Comment by luisgmsft** [comment]
Closing this one because of inactivity. Please re-open if you consider it. Thanks.

**Comment by BenjaminWFox-Lumedic** [comment]
Helped a coworker troubleshoot this error message today, which was caused by issues related to globally installed npm packages & permissions.

We successfully resolved the issue following the steps here: https://johnpapa.net/node-and-npm-without-sudo/ and then re-running `npm install -g @mspnp/azure-building-blocks`
